### ISSUE TITLE
Permanent Alpine.js element throws error: Uncaught (in promise) TypeError: i is not a function

### ISSUE THREAD

**Issue by alexmandrikdev** [hotwired-laravel/turbo-laravel#108]
Hey guys! 

When I make the navigation bar permanent that contains Alpine.js, the app throws this error when I visit a page via Turbo Drive.

![image](https://github.com/hotwired-laravel/turbo-laravel/assets/36386967/6f0b99ed-5711-4924-826f-408fcfb26787)

I'm getting this error from a fresh Laravel Breeze + Turbo Laravel installation (I've followed the [installation guide](https://turbo-laravel.com/docs/1.x/installation)).

The [alpine-turbo-drive-adapter](https://github.com/SimoTod/alpine-turbo-drive-adapter) solves this problem, but it causes issues with the Livewire @entangle directive.

Do you have any ideas on how to fix this problem?

**Comment by tonysm** [comment]
@alexmandrikdev Hey, thanks for reporting. Do you have [this snippet](https://github.com/hotwired-laravel/turbo-laravel/blob/8a27373844530fe55bba6746c733cc62d6e742d5/stubs/resources/js/libs/alpine.js#LL1C1-L20C2) in the Alpine.js setup?

I'm gonna try to reproduce it here.

**Comment by alexmandrikdev** [comment]
> @alexmandrikdev Hey, thanks for reporting. Do you have [this snippet](https://github.com/hotwired-laravel/turbo-laravel/blob/8a27373844530fe55bba6746c733cc62d6e742d5/stubs/resources/js/libs/alpine.js#LL1C1-L20C2) in the Alpine.js setup?
> 
> I'm gonna try to reproduce it here.

Yes, It was added by the `php artisan turbo:install --alpine` command just before the Alpine.js initialization.
![image](https://github.com/hotwired-laravel/turbo-laravel/assets/36386967/42ef3d48-57e9-488a-9d83-ec04c1b1c7cc)

**Comment by tonysm** [comment]
@alexmandrikdev can you move the alpine setup to the `libs/alpine.js` file? And make sure you place it before line 14 there. Let me know if that changes anything.

**Comment by alexmandrikdev** [comment]
> @alexmandrikdev can you move the alpine setup to the `libs/alpine.js` file? And make sure you place it before line 14 there. Let me know if that changes anything.

I've already tried this, but it hasn't solved the problem.

![image](https://github.com/hotwired-laravel/turbo-laravel/assets/36386967/03ea3e50-1a46-4206-b5d7-fb7730660c70)
------
This might be helpful. Every time I navigate to a different page, the event listener is added to the button repeatedly.

![image](https://github.com/hotwired-laravel/turbo-laravel/assets/36386967/6bf528d4-2f99-4f44-b2c1-76e935d48279)
------
By the way, why does the `turbo:install` command put the `initAlpineTurboPermanentFix` function call before the Alpine initialization? Is this on purpose?

**Comment by alexmandrikdev** [comment]
I've published the app on GitHub: https://github.com/alexmandrikdev/laravel-turbo-integration-test.

**Comment by tonysm** [comment]
@alexmandrikdev 

> By the way, why does the turbo:install command put the initAlpineTurboPermanentFix function call before the Alpine initialization? Is this on purpose?

I think that's actually a bug in the installer command. I'm gonna take a look at it.

**Comment by tonysm** [comment]
Hey, I'm gonna close this. Not sure if it's still an issue for you. I have another issue to test with [Livewire 3](https://github.com/hotwired-laravel/turbo-laravel/issues/118) here.
